# Generated by Django 3.2.6 on 2021-08-30 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('era', models.CharField(choices=[('Kyoshi’s Era', 'Kyoshi’s Era'), ('Roku’s Era', 'Roku’s Era'), ('The Hundred Year War', 'The Hundred Year War'), ('Aang’s Era', 'Aang’s Era'), ('Korra’s Era', 'Korra’s Era')], max_length=25)),
                ('scope', models.TextField(null=True)),
                ('group_focus', models.CharField(max_length=255, null=True)),
                ('group_focus_details', models.TextField(null=True)),
                ('act_one', models.TextField(null=True)),
                ('act_two', models.TextField(null=True)),
                ('act_three', models.TextField(null=True)),
                ('non_player_characters', models.TextField(null=True)),
                ('other_notes', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
