# Generated by Django 3.2.6 on 2021-09-01 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playbook', models.CharField(choices=[('The Bold', 'The Bold'), ('The Guardian', 'The Guardian'), ('The Hammer', 'The Hammer'), ('The Icon', 'The Icon'), ('The Idealist', 'The Idealist'), ('The Successor', 'The Successor')], max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('demeanor', models.CharField(choices=[('Military', 'Military'), ('Monastic', 'Monastic'), ('Outlaw', 'Outlaw'), ('Privileged', 'Privileged'), ('Urban', 'Urban'), ('Wilderness', 'Wilderness'), ('Impatient', 'Impatient'), ('Sensitive', 'Sensitive'), ('Affable', 'Affable'), ('Enthusiastic', 'Enthusiastic'), ('Talkative', 'Talkative'), ('Impetuous', 'Impetuous')], max_length=15)),
                ('training', models.CharField(choices=[('Waterbending', 'Waterbending'), ('Firebending', 'Firebending'), ('Earthbending', 'Earthbending'), ('Airbending', 'Airbending'), ('Weapons', 'Weapons'), ('Technology', 'Technology')], max_length=15)),
                ('creativity', models.IntegerField(blank=True, null=True)),
                ('focus', models.IntegerField(blank=True, null=True)),
                ('harmony', models.IntegerField(blank=True, null=True)),
                ('passion', models.IntegerField(blank=True, null=True)),
                ('fatigue', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-3)])),
                ('afraid', models.BooleanField(default=False)),
                ('angry', models.BooleanField(default=False)),
                ('foolish', models.BooleanField(default=False)),
                ('guilty', models.BooleanField(default=False)),
                ('insecure', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign')),
            ],
        ),
    ]
