# Generated by Django 3.2.6 on 2021-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.CharField(choices=[('Bold', 'The Bold'), ('Guardian', 'The Guardian'), ('Hammer', 'The Hammer'), ('Icon', 'The Icon'), ('Idealist', 'The Idealist'), ('Successor', 'The Successor')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('demeanor', models.CharField(choices=[('Military', 'Military'), ('Monastic', 'Monastic'), ('Outlaw', 'Outlaw'), ('Privileged', 'Privileged'), ('Urban', 'Urban'), ('Wilderness', 'Wilderness'), ('Impatient', 'Impatient'), ('Sensitive', 'Sensitive'), ('Affable', 'Affable'), ('Enthusiastic', 'Enthusiastic'), ('Talkative', 'Talkative'), ('Impetuous', 'Impetuous')], max_length=15)),
                ('training', models.CharField(choices=[('Waterbending', 'Waterbending'), ('Firebending', 'Firebending'), ('Earthbending', 'Earthbending'), ('Airbending', 'Airbending'), ('Weapons', 'Weapons'), ('Technology', 'Technology')], max_length=15)),
                ('creativity', models.IntegerField()),
                ('focus', models.IntegerField()),
                ('harmony', models.IntegerField()),
                ('passion', models.IntegerField()),
            ],
        ),
    ]
