# Generated by Django 3.2.6 on 2021-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0003_alter_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='creativity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='focus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='harmony',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='passion',
            field=models.IntegerField(null=True),
        ),
    ]
