# Generated by Django 3.2.6 on 2021-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0004_auto_20210827_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='playbook',
            field=models.CharField(choices=[('The Bold', 'The Bold'), ('The Guardian', 'The Guardian'), ('The Hammer', 'The Hammer'), ('The Icon', 'The Icon'), ('The Idealist', 'The Idealist'), ('The Successor', 'The Successor')], max_length=15),
        ),
    ]
