# Generated by Django 3.2.6 on 2021-08-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210830_0842'),
        ('charsheet', '0006_character_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='creativity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='focus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='harmony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='passion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
