# Generated by Django 3.2.6 on 2021-08-30 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0007_auto_20210830_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fatigue',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
