# Generated by Django 3.2.6 on 2021-08-30 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0008_character_fatigue'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-3)]),
        ),
    ]
