# Generated by Django 3.2.6 on 2021-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0009_character_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='afraid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='angry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='foolish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='guilty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='insecure',
            field=models.BooleanField(default=False),
        ),
    ]
